# Generated by Django 4.2.11 on 2024-04-26 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(upload_to='question/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='subject_photo/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_duretion_minuts', models.DurationField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='topics_photo/')),
                ('description', models.TextField()),
                ('quetion_type', models.CharField(choices=[('HARD', 'HARD'), ('MEDIOM', 'MEDIOUM'), ('EASY', 'EASY')], max_length=20)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_duration_minuts', models.TimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.test')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_time', models.DateTimeField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], editable=False, max_length=10)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.question')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.results')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.topics'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.question')),
            ],
        ),
    ]
