# Generated by Django 4.2.11 on 2024-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0002_alter_results_scheduled_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_duretion_minuts',
            field=models.TimeField(),
        ),
    ]
