# Generated by Django 4.2.11 on 2024-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='topics',
            name='quetion_type',
            field=models.CharField(choices=[('HARD', 'HARD'), ('MEDIOM', 'MEDIOUM'), ('EASY', 'EASY')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
