# Generated by Django 4.2.11 on 2024-04-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0003_alter_test_test_duretion_minuts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_duretion_minuts',
            new_name='duretion',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='test_duration_minuts',
            new_name='duretion',
        ),
    ]
