# Generated by Django 4.2.11 on 2024-04-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0004_rename_test_duretion_minuts_test_duretion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='duretion',
        ),
    ]
