# Generated by Django 4.2.11 on 2024-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0005_remove_testquestion_duretion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanswer',
            name='is_correct',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='UNCOMPLETED', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='results',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
