# Generated by Django 4.2.11 on 2024-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0006_alter_resultanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duretion',
            field=models.DurationField(),
        ),
    ]
