# Generated by Django 4.2.11 on 2024-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0008_alter_test_duretion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duretion',
            field=models.DurationField(),
        ),
    ]
