# Generated by Django 4.2.11 on 2024-05-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ort_test', '0011_alter_resultanswer_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.results')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ort_test.topics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
