# Generated by Django 4.2.11 on 2024-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ort_test', '0012_resultanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanalysis',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultanalysis',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
